# Generated by Django 4.2.1 on 2023-05-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TapbitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=8)),
                ('rebate', models.CharField(max_length=200)),
                ('upper_rebate', models.CharField(max_length=200)),
                ('total_rebate', models.CharField(max_length=200)),
            ],
        ),
    ]
